<?php 
?>
<a href="javascript:grin('[F1]')" title="微笑"><img src="<?php echo TEMPLATE_URL; ?>images/face/1.png" alt="微笑"/></a>
<a href="javascript:grin('[F2]')" title="大笑"><img src="<?php echo TEMPLATE_URL; ?>images/face/2.png" alt="大笑"/></a>
<a href="javascript:grin('[F3]')" title="嘴馋"><img src="<?php echo TEMPLATE_URL; ?>images/face/3.png" alt="嘴馋"/></a>
<a href="javascript:grin('[F4]')" title="惊诈"><img src="<?php echo TEMPLATE_URL; ?>images/face/4.png" alt="惊诈"/></a>
<a href="javascript:grin('[F5]')" title="呕吐"><img src="<?php echo TEMPLATE_URL; ?>images/face/5.png" alt="呕吐"/></a>
<a href="javascript:grin('[F6]')" title="亲吻"><img src="<?php echo TEMPLATE_URL; ?>images/face/6.png" alt="亲吻"/></a>
<a href="javascript:grin('[F7]')" title="卖萌"><img src="<?php echo TEMPLATE_URL; ?>images/face/7.png" alt="卖萌"/></a>
<a href="javascript:grin('[F8]')" title="略气"><img src="<?php echo TEMPLATE_URL; ?>images/face/8.png" alt="略气"/></a>
<a href="javascript:grin('[F9]')" title="疑问"><img src="<?php echo TEMPLATE_URL; ?>images/face/9.png" alt="疑问"/></a>
<a href="javascript:grin('[F10]')" title="厉害"><img src="<?php echo TEMPLATE_URL; ?>images/face/10.png" alt="厉害"/></a>
<a href="javascript:grin('[F11]')" title="委屈"><img src="<?php echo TEMPLATE_URL; ?>images/face/11.png" alt="委屈"/></a>
<a href="javascript:grin('[F12]')" title="愤怒"><img src="<?php echo TEMPLATE_URL; ?>images/face/12.png" alt="愤怒"/></a>
<a href="javascript:grin('[F13]')" title="黑线"><img src="<?php echo TEMPLATE_URL; ?>images/face/13.png" alt="黑线"/></a>
<a href="javascript:grin('[F14]')" title="难过"><img src="<?php echo TEMPLATE_URL; ?>images/face/14.png" alt="难过"/></a>
<a href="javascript:grin('[F15]')" title="汗颜"><img src="<?php echo TEMPLATE_URL; ?>images/face/15.png" alt="汗颜"/></a>
<a href="javascript:grin('[F16]')" title="滑稽"><img src="<?php echo TEMPLATE_URL; ?>images/face/16.png" alt="滑稽"/></a>
<a href="javascript:grin('[F17]')" title="大哭"><img src="<?php echo TEMPLATE_URL; ?>images/face/17.png" alt="大哭"/></a>
<a href="javascript:grin('[F18]')" title="装酷"><img src="<?php echo TEMPLATE_URL; ?>images/face/18.png" alt="装酷"/></a>
<a href="javascript:grin('[F19]')" title="偷笑"><img src="<?php echo TEMPLATE_URL; ?>images/face/19.png" alt="偷笑"/></a>
<a href="javascript:grin('[F20]')" title="倦意"><img src="<?php echo TEMPLATE_URL; ?>images/face/20.png" alt="倦意"/></a>
<a href="javascript:grin('[F21]')" title="腼腆"><img src="<?php echo TEMPLATE_URL; ?>images/face/21.png" alt="腼腆"/></a>
<a href="javascript:grin('[F22]')" title="惊讶"><img src="<?php echo TEMPLATE_URL; ?>images/face/22.png" alt="惊讶"/></a>
<a href="javascript:grin('[F23]')" title="噗~"><img src="<?php echo TEMPLATE_URL; ?>images/face/23.png" alt="噗~"/></a>
<a href="javascript:grin('[F24]')" title="奸笑"><img src="<?php echo TEMPLATE_URL; ?>images/face/24.png" alt="奸笑"/></a>
<a href="javascript:grin('[F25]')" title="眩晕"><img src="<?php echo TEMPLATE_URL; ?>images/face/25.png" alt="眩晕"/></a>
<a href="javascript:grin('[F26]')" title="抠鼻"><img src="<?php echo TEMPLATE_URL; ?>images/face/26.png" alt="抠鼻"/></a>
<a href="javascript:grin('[F27]')" title="打脸"><img src="<?php echo TEMPLATE_URL; ?>images/face/27.png" alt="打脸"/></a>
<a href="javascript:grin('[F28]')" title="有神"><img src="<?php echo TEMPLATE_URL; ?>images/face/28.png" alt="有神"/></a>
<a href="javascript:grin('[F29]')" title="爱心"><img src="<?php echo TEMPLATE_URL; ?>images/face/29.png" alt="爱心"/></a>
<a href="javascript:grin('[F30]')" title="心碎"><img src="<?php echo TEMPLATE_URL; ?>images/face/30.png" alt="心碎"/></a>
<a href="javascript:grin('[F31]')" title="污桐币"><img src="<?php echo TEMPLATE_URL; ?>images/face/31.png" alt="污桐币"/></a>
<a href="javascript:grin('[F32]')" title="灵感"><img src="<?php echo TEMPLATE_URL; ?>images/face/32.png" alt="灵感"/></a>
<a href="javascript:grin('[F33]')" title="咖啡"><img src="<?php echo TEMPLATE_URL; ?>images/face/33.png" alt="咖啡"/></a>
<a href="javascript:grin('[F34]')" title="Okey"><img src="<?php echo TEMPLATE_URL; ?>images/face/34.png" alt="Okey"/></a>
<a href="javascript:grin('[F35]')" title="吃西瓜"><img src="<?php echo TEMPLATE_URL; ?>images/face/35.png" alt="吃西瓜"/></a>
<a href="javascript:grin('[F36]')" title="吃翔"><img src="<?php echo TEMPLATE_URL; ?>images/face/36.png" alt="吃翔"/></a>
<a href="javascript:grin('[F37]')" title="囧"><img src="<?php echo TEMPLATE_URL; ?>images/face/37.png" alt="囧"/></a>
<a href="javascript:grin('[F38]')" title="你小子"><img src="<?php echo TEMPLATE_URL; ?>images/face/38.png" alt="你小子"/></a>
<a href="javascript:grin('[F39]')" title="药丸"><img src="<?php echo TEMPLATE_URL; ?>images/face/39.png" alt="药丸"/></a>
<a href="javascript:grin('[F40]')" title="红领巾"><img src="<?php echo TEMPLATE_URL; ?>images/face/40.png" alt="红领巾"/></a>